public enum GameEventType
{
    HISTORY,
    INTERACTION_ADVANCE,
    INVENTORY_SELL,
    NEXT_DAILY_EVENT,
    BEGIN_DAY,
    END_DAY,
    OPEN_SHOP,
    CLOSE_SHOP,
    VISITOR_ARRIVAL,
    VISITOR_DEPARTURE,
    PAPER_ARRIVED,
    BANK_WITHDRAWAL,
    CHARACTER_TIDBIT_UNLOCKED,
    BOOK_ORDER,
    STAMP_COLLECTED
}