public enum GameEventType
{
    HISTORY,
    INTERACTION_ADVANCE,
    INVENTORY_SELL,
    NEXT_DAILY_EVENT,
    BEGIN_DAY,
    END_DAY,
    OPEN_SHOP,
    CLOSE_SHOP,
    VISITOR_ARRIVAL,
    VISITOR_DEPARTURE,
}