public enum RequirementType
{
    HISTORY,
    INVENTORY_CONTAINS,
    INVENTORY_EMPTY,
    INVENTORY_NOT_EMPTY,
    BANK_BALANCE_AVAILABLE,
    BOOK_WITH_ITEM,
    BOOK_WITH_SOME_ITEM,
    CAN_AFFORD_TAXES
}